language: node_js
node_js:
- '0.10'
before_script:
- npm install
script:
- npm test
notifications:
  hipchat:
    rooms:
      secure: Ueh7QRz/ymKPfuK21rGeWUhfSwFxRXJcIMYkP3y0FfWcG2Iww4cZKpgn7IPHXEIPQ6c9qLAJuzwInrmS1r79vNt587U+CLoRY+ozT2I8BNqa+7/9RTUxOD5MUZ5vJgzL09ZAudP2byr3/zIzEpRhUMz99QInKXO1msCmM+Z/6Jg=
